---
- name: Install fapolicyd packages
  yum:
    name:
      - fapolicyd
      - fapolicyd-selinux
    state: present

- name: Gather package facts
  package_facts:

- name: Copy fapolicyd configuration file
  copy:
    src: "{{ fapolicyd_setup_config_file }}"
    dest: /etc/fapolicyd/fapolicyd.conf
    owner: root
    group: fapolicyd
    mode: '0644'
  register: daemon_config
  when: fapolicyd_setup_config_file | default(false)

- name: Copy fapolicyd rules file
  copy:
    src: "{{ fapolicyd_setup_rules_file }}"
    dest: /etc/fapolicyd/rules.d/zz-ansible.rules
    owner: root
    group: fapolicyd
    mode: '0644'
  register: rules_config
  when: fapolicyd_setup_rules_file | default(false)

- name: Remove old fapolicyd rules file
  file:
    path: /etc/fapolicyd/fapolicyd.rules
    state: absent
  when: fapolicyd_setup_rules_file | default(false)

- name: Copy fapolicyd trust file
  copy:
    src: "{{ fapolicyd_setup_trust_file }}"
    dest: /etc/fapolicyd/trust.d/zz-ansible.trust
    owner: root
    group: fapolicyd
    mode: '0644'
  register: trust_config
  when: fapolicyd_setup_trust_file | default(false)

- name: Copy fapolicyd RPM filter file
  copy:
    src: "{{ fapolicyd_setup_rpm_filter_file }}"
    dest: /etc/fapolicyd/rpm-filter.conf
    owner: root
    group: fapolicyd
    mode: '0644'
  register: rpm_filter_config
  when: fapolicyd_setup_rpm_filter_file | default(false)

- name: Run fapolicyd configuration check
  command: fapolicyd-cli --check-config
  check_mode: false
  changed_when: false
  when: "'fapolicyd' in ansible_facts.packages"

- name: Enable fapolicyd service
  service:
    name: fapolicyd
    enabled: true
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - fapolicyd_setup_enable_service | bool

- name: Start fapolicyd service
  service:
    name: fapolicyd
    state: started
  register: service_start
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - fapolicyd_setup_enable_service | bool

- name: Restart fapolicyd to apply configuration changes
  service:
    name: fapolicyd
    state: restarted
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - fapolicyd_setup_enable_service | bool
    - service_start is not changed
    - daemon_config is changed or
      rules_config is changed or
      trust_config is changed or
      rpm_filter_config is changed
