---
- name: Install fapolicyd packages
  yum:
    name:
      - fapolicyd
      - fapolicyd-selinux
    state: present

- name: Gather package facts
  package_facts:

- name: Copy fapolicyd configuration file
  template:
    src: "{{ fapolicyd_setup_config_file }}.j2"
    dest: /etc/fapolicyd/fapolicyd.conf
    owner: root
    group: fapolicyd
    mode: '0644'
  register: daemon_config
  when:
    - fapolicyd_setup_config_file | default(false)
    - ansible_facts.distribution_version | float < 8.3

- name: Run fapolicyd configuration check
  command: fapolicyd-cli --check-config
  check_mode: false
  changed_when: false
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - ansible_facts.distribution_version | float >= 8.6

- name: Add file to trustdb
  command: fapolicyd-cli --file add {{ item }}
  check_mode: false
  changed_when: false
  loop: "{{ fapolicyd_add_trusted_file if fapolicyd_add_trusted_file is iterable else [] }}"
  when:
    - fapolicyd_add_trusted_file
    - ansible_facts.distribution_version | float >= 8.4

- name: Remove file from trustdb
  command: fapolicyd-cli --file delete {{ item }}
  check_mode: false
  changed_when: false
  loop: "{{ fapolicyd_remove_trusted_file if fapolicyd_remove_trusted_file is iterable else [] }}"
  when:
    - fapolicyd_remove_trusted_file
    - ansible_facts.distribution_version | float >= 8.4

- name: Update file in trustdb
  command: fapolicyd-cli --file update {{ item }}
  check_mode: false
  changed_when: false
  loop: "{{ fapolicyd_update_trusted_file if fapolicyd_update_trusted_file is iterable else [] }}"
  when:
    - fapolicyd_update_trusted_file
    - ansible_facts.distribution_version | float >= 8.4

- name: Enable fapolicyd service
  service:
    name: fapolicyd
    enabled: true
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - fapolicyd_setup_enable_service | bool

- name: Start fapolicyd service
  service:
    name: fapolicyd
    state: started
  register: service_start
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - fapolicyd_setup_enable_service | bool

- name: Restart fapolicyd to apply configuration changes
  service:
    name: fapolicyd
    state: restarted
  when:
    - "'fapolicyd' in ansible_facts.packages"
    - fapolicyd_setup_enable_service | bool
    - service_start is not changed
    - daemon_config is changed
