---
#- name: Check trust compatibility
#  fail:
#    msg: Old fapolicyd does not support trust setting
#  when:
#    - fapolicyd_setup_trust
#    - ansible_facts.distribution_version is version("8.2", "<=")

#- name: Check integrity compatibility
#  fail:
#    msg: Old fapolicyd does not support integrity setting
#  when:
#    - fapolicyd_setup_integrity
#    - ansible_facts.distribution_version is version("8.3", "<=")

- name: Install fapolicyd packages
  package:
    name:
      - fapolicyd
    state: present

- name: Install fapolicyd-selinux packages
  package:
    name:
      - fapolicyd-selinux
    state: present
  when:
    - ansible_facts.distribution_version is version("8.3", ">=")

- name: Copy fapolicyd configuration file
  template:
    src: fapolicyd.conf.j2
    dest: /etc/fapolicyd/fapolicyd.conf
    owner: root
    group: fapolicyd
    mode: '0644'
  register: daemon_config
#  when:
#    - ansible_facts.distribution_version is version("8.3", ">=")

- name: Run fapolicyd configuration check
  command: fapolicyd-cli --check-config
  check_mode: false
  changed_when: false
  when:
    - ansible_facts.distribution_version is version("8.6", ">=")

- name: Trustdb cleanup
  command: fapolicyd-cli --file delete /
  when:
    - fapolicyd_add_trusted_file
    - ansible_facts.distribution_version is version("8.4", ">=")
  failed_when: false

- name: Add file to trustdb
  command: fapolicyd-cli --file add {{ item | quote }}
  loop: "{{ fapolicyd_add_trusted_file if fapolicyd_add_trusted_file is iterable else [] }}"
  when:
    - fapolicyd_add_trusted_file
    - ansible_facts.distribution_version is version("8.4", ">=")
  failed_when: false

- name: Enable fapolicyd service
  service:
    name: fapolicyd
    enabled: true
  when:
    - fapolicyd_setup_enable_service

- name: Start fapolicyd service
  service:
    name: fapolicyd
    state: started
  register: service_start
  when:
    - fapolicyd_setup_enable_service

- name: Not starting fapolicyd
  service:
    name: fapolicyd
    state: stopped
  when:
    - not fapolicyd_setup_enable_service
