---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Enable fapolicyd
  include_tasks: enable.yml
  when:
    - ansible_facts.distribution_version is version("8.1", ">=")
